language: python

python: "2.7"

sudo: false

# command to install dependencies
install:
  - easy_install -U pip
  - pip install PyYAML argparse
  - pip install catkin_pkg ros_buildfarm rosdistro nose coverage
  - pip install unidiff

# command to run tests
script: nosetests -s

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
      - strands-devel
